# Generated by Django 3.2.3 on 2021-06-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infile',
            old_name='infile_path',
            new_name='labfile_path',
        ),
        migrations.AddField(
            model_name='infile',
            name='unlabfile_path',
            field=models.FileField(default='default.csv', max_length=200, upload_to='indir'),
            preserve_default=False,
        ),
    ]
